name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Backend build and run
      run: |
          cd Kudos-Board-Backend
          npm ci
          npm run build
          npm test
    - name: Frontend build and run
      run: |
          cd Kudos-Board-Frontend
          npm ci
          npm run build
          npm test
