name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install Backend modules
      run: npm ci
    - name: build backend
      run: npm run build
    - name: Run tests
      run: npm test
    - name: Install Frontend modules
      run: npm ci
    - name: build frontend
      run: npm run build
    - name: Run tests
      run: npm test
